# Generated by Django 3.2.16 on 2022-11-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=60, null=True, verbose_name='Фамилия')),
                ('description', models.TextField(blank=True, max_length=222, verbose_name='Описание')),
                ('img', models.ImageField(null=True, upload_to='images/students/', verbose_name='Фото студента')),
                ('country', models.CharField(max_length=222, null=True, verbose_name='Куда поступил')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=60, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=150, null=True, verbose_name='Электронный адрес')),
                ('content', models.TextField(blank=True, verbose_name='Вопросы')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('img', models.ImageField(null=True, upload_to='images/university/', verbose_name='Фото университета')),
                ('country', models.CharField(max_length=222, null=True, verbose_name='Место положение')),
                ('link', models.CharField(max_length=300, null=True, verbose_name='Ссылка сайта университета')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
    ]
